In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("FotData 환경 정상 작동")

FotData 환경 정상 작동


In [2]:
np.__version__, pd.__version__

('2.2.5', '2.3.3')

In [3]:
data = {
    "home_team": ["A", "B", "C", "A", "B", "C"],
    "away_team": ["B", "C", "A", "C", "A", "B"],
    "home_goals": [2, 1, 3, 0, 2, 4],
    "away_goals": [1, 2, 1, 1, 3, 2]
}

df = pd.DataFrame(data)
df

home_team away_team  home_goals  away_goals
0         A         B           2           1
1         B         C           1           2
2         C         A           3           1
3         A         C           0           1
4         B         A           2           3
5         C         B           4           2

In [4]:
df["home_goals"].mean()

np.float64(2.0)

In [5]:
df[df["home_goals"] > df["away_goals"]]

home_team away_team  home_goals  away_goals
0         A         B           2           1
2         C         A           3           1
5         C         B           4           2

In [6]:
df.groupby("home_team")["home_goals"].mean()

home_team
A    1.0
B    1.5
C    3.5
Name: home_goals, dtype: float64

In [7]:
df["home_win"] = df["home_goals"] > df["away_goals"]

In [8]:
df.groupby("home_team")["home_win"].mean()

home_team
A    0.5
B    0.0
C    1.0
Name: home_win, dtype: float64

In [9]:
df["result"] = df.apply(
    lambda x: "H" if x["home_goals"] > x["away_goals"]
    else "D" if x["home_goals"] == x["away_goals"]
    else "A",
    axis=1
)

df

home_team away_team  home_goals  away_goals  home_win result
0         A         B           2           1      True      H
1         B         C           1           2     False      A
2         C         A           3           1      True      H
3         A         C           0           1     False      A
4         B         A           2           3     False      A
5         C         B           4           2      True      H

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["result_encoded"] = le.fit_transform(df["result"])

df

home_team away_team  home_goals  away_goals  home_win result  result_encoded
0         A         B           2           1      True      H               1
1         B         C           1           2     False      A               0
2         C         A           3           1      True      H               1
3         A         C           0           1     False      A               0
4         B         A           2           3     False      A               0
5         C         B           4           2      True      H               1

In [11]:
X = df[["home_goals", "away_goals"]]
y = df["result_encoded"]

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [13]:
model.predict(X)

array([1, 0, 1, 0, 0, 1])

In [14]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X)
accuracy_score(y, y_pred)

1.0

In [15]:
model.predict_proba(X)

array([[0.38031403, 0.61968597],
       [0.77183736, 0.22816264],
       [0.18041381, 0.81958619],
       [0.8267041 , 0.1732959 ],
       [0.7057817 , 0.2942183 ],
       [0.13502069, 0.86497931]])

In [16]:
new_game = [[2, 0]]  # 홈 2골, 원정 0골
model.predict(new_game), model.predict_proba(new_game)

C:\Users\USER\miniconda3\envs\fotdata\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\USER\miniconda3\envs\fotdata\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


(array([1]), array([[0.23688837, 0.76311163]]))

In [17]:
new_game = pd.DataFrame([[2, 0]], columns=["home_goals", "away_goals"])
model.predict(new_game), model.predict_proba(new_game)

(array([1]), array([[0.23688837, 0.76311163]]))

In [18]:
new_game = pd.DataFrame([[0, 3]], columns=["home_goals", "away_goals"])
model.predict(new_game), model.predict_proba(new_game)

(array([0]), array([[0.94909974, 0.05090026]]))